version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: 'daily'
      timezone: 'Europe/Riga'
    open-pull-requests-limit: 15
    reviewers:
      - sergeyrocks
