name: Deploy

#on:
#  push:
#    branches:
#      - main
on: pull_request

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
#          heroku_email: ${{secrets.HEROKU_EMAIL}}
#          procfile: ${{secrets.HEROKU_PROCFILE}}
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{secrets.HEROKU_PROCFILE}} | sed 's/./& /g'
